version: '2.2'

services:

  imagination_server:
    image: imagination-server
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    mem_limit: 512m
    mem_reservation: 512m
    depends_on:
      - jaeger
      - httpbin

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268/tcp"
      - "14250:14250/tcp"
      - "16686:16686"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
